# Generated by Django 4.1 on 2022-10-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('feed', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=80)),
                ('Ano', models.IntegerField()),
                ('edate', models.CharField(max_length=80)),
                ('cvv', models.CharField(max_length=3)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='payment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='postpaids',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=70)),
                ('calls', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=70)),
                ('validity', models.CharField(max_length=70)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='postpayment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=70)),
                ('Ano', models.IntegerField()),
                ('edate', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='postrecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=70)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=1000)),
                ('Amount', models.CharField(max_length=60)),
                ('date', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='prepaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=70)),
                ('calls', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=70)),
                ('validity', models.CharField(max_length=70)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='prepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=80)),
                ('pname', models.CharField(max_length=30)),
                ('Ano', models.IntegerField()),
                ('edate', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('mobile', models.IntegerField()),
                ('date', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('query', models.TextField()),
                ('phone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='recs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=70)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
